name: dbt-pipeline-$(Date:yyyy-MM-dd)

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - dbt_practice_job

pool:
  vmImage: "ubuntu-latest"
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install dbt-databricks
    displayName: 'Install dependencies'

  - script: |
      dbt test
    displayName: 'Run dbt test'